[package]
name = "nvvec-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nvvec-core = { workspace = true }
nvvec-index = { workspace = true }
nvvec-io = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rayon = { workspace = true }
